Fix font installation warnings on nilrt/master/next
ni/openembedded-core pull request #129
Opened 2024-07-15 12:23 UTC by pratheekshasn

Building the branch nilrt/master/next threw a whole lot of warnings related to installing fonts on the target, as listed below:

`WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-util.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-adobe-100dpi.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-adobe-utopia-100dpi.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-bh-100dpi.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-bh-lucidatypewriter-100dpi.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-bitstream-100dpi.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: ttf-pt-sans.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-cursor-misc.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs: font-misc-misc.postinst returned 127, marking as unpacked only, configuration required on target. 
WARNING: nilrt-runmode-rootfs-1.0-r0 do_rootfs:  configuration required on target.`

The postinst script logic seemed to error out while running in a rootfs context, and it needs to be delayed until the device is first booting.

## Fix
The `pkg_postinst` in the recipe is replaced with `pkg_postinst_ontarget`.

Details in [this](https://docs.yoctoproject.org/dev-manual/new-recipe.html?highlight=pkg_postinst_ontarget#post-installation-scripts) link.

The change in the current PR takes care of all the warnings in the list, except for ttf-pt-sans, which is fixed in this PR.

Signed-off by: Pratheeksha S N <pratheeksha.s.n@ni.com>

2024-07-15 18:27 UTC, chaitu236 requested changes
Changes look ok, but shouldn't this target next branch?
Please add AB# in PR description.

Are you planning to send this upstream?

2024-07-15 18:29 UTC, amstewart requested changes
Same feedback as [here](https://github.com/ni/meta-openembedded/pull/60#pullrequestreview-2178389233).

2024-09-30 21:37 UTC, erickshepherdNI commented
I investigated the cause of the font warnings and it looks like the build expects the font cache to present on the target and only finds it when using pkg_postinst_ontarget. I'm not sure if the recipes could be updated to get around this but I talked with @gratian and using pkg_postinst_ontarget seems like a good solution in this case. I have some more details in the related work item: https://dev.azure.com/ni/DevCentral/_workitems/edit/2812142

2025-01-13 20:06 UTC, closed without merging

2025-01-13 20:06 UTC, chaitu236 commented
Closing since this was merged in https://github.com/ni/openembedded-core/pull/139.