Dev/versioned kernel devsrc review
ni/openembedded-core pull request #14
Opened 2020-11-25 05:24 UTC by chaitu236

Cherry-picked commits from dunfell that touched kernel-devsrc recipe.
Split kernel-devsrc into an inc file and added changes to support building it for multiple kernel versions.

@ni/rtos

2020-11-30 22:06 UTC, amstewart requested changes
I approve of the cherry-picks and `kernel-devsrc` split. I think most of the other commits here would actually be better as meta-nilrt commits - since they don't seem readily upstreamable and will probably conflict whenever we do a rebase.

2020-11-30 22:06 UTC, amstewart commented on meta/classes/kernel.bbclass
> +
To avoid the hassle of maintaining this out-of-stream, could you refactor it as an independent task of the `linux-nilrt-next.inc` includes in meta-nilrt? eg...
```
do_copy_kernel_builddir() {
    cp ...
    ...
}

addtask copy_kernel_builddir before do_deploy
```

2020-11-30 22:06 UTC, amstewart commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +
Seems like this file is a concat of (a) the upstream contents of `kernel-devsrc.bb` and (b) the new fix for NI's internal `kernel-devsrc` needs (objtool). If we pull it as-is, every upstream change to `kernel-devsrc` is going to conflict with this patchset.

Instead, can you break the the commit into each part so that we can pursue upstreaming part (a) - since they should also see the wisdom in using an includes for the kernel-devsrc package. Part (b) might be upstreamable as well; but if not, we should try moving it to a separate includes in meta-nilrt and append it to our recipes as needed.

2020-11-30 22:06 UTC, amstewart commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +   make modules_prepare
Is the intention to send this stanza upstream? I [don't think](https://github.com/openembedded/openembedded-core/search?q=pkg_postinst_ontarget.*) OE-core has any other instances where they use `pkg_postinst_ontarget` (since OE upstream doesn't really support runtime package installation).

So I guess we can try to send it upstream and see what they say, but I imagine that we will need to instead convert it into a meta-nilrt commit - a la. your sibling commit [here](https://github.com/ni/meta-nilrt/pull/63/commits/4206603295aaf622ab4de298dddfaa0baceb66ce#diff-8c6f7e2d86c5211c5c3f529b8e3cff554b82495724a51bb6bb7c429bbdd81e18).

2020-12-02 18:54 UTC, chaitu236 commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +   make modules_prepare
Yes, I wanted to send this upstream. I guess it is better to convert it to meta-nilrt commit right now and revert it later if this gets accepted in OE upstream.

2020-12-02 19:12 UTC, chaitu236 commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +
Actually except for https://github.com/ni/openembedded-core/pull/14/commits/67e766dd2faaa63a24daa966743e3d4c14939a07 and some minor changes like using KERNEL_DEPENDENCY, KERNEL_DIRECTORY and KERNEL_BUILD_DIRECTORY, this file is same as the one in dunfell. All objtool changes we made [were in meta-nilrt](https://github.com/ni/meta-nilrt/pull/21).

2020-12-02 21:29 UTC, chaitu236 commented on meta/classes/kernel.bbclass
> +
https://github.com/ni/meta-nilrt/pull/68

2020-12-02 21:29 UTC, chaitu236 commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +   make modules_prepare
https://github.com/ni/meta-nilrt/pull/68

2020-12-03 20:44 UTC, amstewart commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +
OK. So is the plan to also merge the meta-nilrt changes with dunfell, where oe-core already has the devsrc changes you are making here?

2020-12-03 21:09 UTC, chaitu236 commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +
oe-core dunfell is missing https://github.com/ni/openembedded-core/pull/14/commits/a97a9943b227610c733bebaee26d13f019a582db so will raise PR for that, and also PR for meta-nilrt changes from sumo to dunfell.

2020-12-03 21:27 UTC, amstewart commented on meta/recipes-kernel/linux/kernel-devsrc.inc
> +
OK. We need to try and upstream that commit (a97a994). Otherwise, it will be a pain to rebase in the future.

2020-12-03 21:28 UTC, merged