Cherry pick python3-unittest-automake-output recipe
ni/openembedded-core pull request #140
Opened 2024-10-04 13:26 UTC by texasaggie97

# Summary of Changes
Cherry pick recipe for `python3-unittest-automake-output`. This is required for ni/meta-nilrt#742

# Justification
Since the NILRT 11.0 release has been delayed, SNAC v1.0 must rebase to NILRT 10 to affect a 25Q1 release.

# Testing
[X] I have built the core package feed with this PR in place. (`bitbake packagefeed-ni-core`) - This allows the referenced PR above to build
[X] I certify that the contents of this pull request complies with the [Developer Certificate of Origin](https://github.com/ni/nilrt/blob/HEAD/docs/CONTRIBUTING.md#developer-certificate-of-origin-dco).

2024-10-04 14:39 UTC, amstewart approved these changes

2024-10-04 14:40 UTC, amstewart requested changes
Actually, could you redo the cherry-picks with `-x`, so that git will add information to the commit message about where these came from?

2024-10-07 21:25 UTC, texasaggie97 commented
> Actually, could you redo the cherry-picks with `-x`, so that git will add information to the commit message about where these came from?

This is done

2024-10-07 21:26 UTC, texasaggie97 commented
Patch v2
Cherry pick with `-x` parameter

2024-10-08 14:19 UTC, amstewart approved these changes

2024-10-08 14:19 UTC, merged