opkg-utils: split package so scripts can be installed individually
ni/openembedded-core pull request #21
Opened 2021-05-18 18:22 UTC by bstreiff

Not all scripts in opkg-utils require python3 as a dependency; some of
them are implemented in shell and only require that. This commit splits
the opkg-utils package into several subpackages so that individual
scripts can be included without requiring all scripts, particularly the
ones that require a python3 runtime.

For compatibility, the opkg-utils package itself continues to exist as
a metapackage that depends on all its subpackages so that installing
"opkg-utils" would install all the things it would before.

Signed-off-by: Brandon Streiff <brandon.streiff@ni.com>

2021-05-18 18:32 UTC, bstreiff commented
Output from `opkg-make-index` on the `opkg-utils*.ipk` packages is here: https://gist.github.com/bstreiff/9986ebf6bc4f00d6287480b4fa4bfe7b

I wasn't sure how much resolution I should use in splitting up packages. We only need `opkg-feed` for our usage, but splitting out just one package seemed weird. I opted to make each script its own package, which feels _slightly_ excessive and results in a bunch of packages for which the package overhead probably exceeds the contents within. I couldn't come up with a good strategy for a "middle ground".

I did track inner dependencies for "scripts that call other scripts". I didn't dig that deeply with the python module dependencies-- those just get grouped under `opkg-utils-python-support`.

2021-05-20 16:33 UTC, amstewart requested changes
I think I agree that splitting nearly every script into its own subpackage is a little excessive. And it seems like it would be a special pain whenever we add new content.

What about grouping all the bash and python scripts into an `opkg-utils-shell-tools` and `opkg-utils-python-tools` subpackage respectively. It seems to me like that is a more reasonable level of granularity for builders.

2021-05-20 20:50 UTC, bstreiff commented
Updated commit. New package list: https://gist.github.com/bstreiff/9986ebf6bc4f00d6287480b4fa4bfe7b

2021-05-20 21:46 UTC, amstewart approved these changes
Looks good to me.

2021-05-20 21:56 UTC, merged