image_types: Remove leading './' in tar image archives
ni/openembedded-core pull request #54
Opened 2022-05-27 20:17 UTC by shruthi-ravi

The leading './' makes it difficult to provide relative paths to tar during the untar operation.
For example, `tar xvf --exclude=usr/bin` does not apply correctly to the files in the archive because they are prefixed with a './'. As an alternative to applying './' to all the exclude paths, remove the leading './' when creating the tar archive.

Notes:
- This change fixes azdo bug [1963519](https://ni.visualstudio.com/DevCentral/_boards/board/t/RTOS/Work%20Items/?workitem=1963519). Targets reconnect to the salt master after a hardknott image reinstallation.
- This is not a new problem in the archive. It has always existed and the --exclude options in the nisystemimage script have not been applied correctly. The issue has come up now because the new hardknott image contains a master.conf that tar installs over the existing master.conf in the old image. This problem did not exist in sumo because the sumo image did not contain a master.conf file. The file is installed to the image as part of a package in the hardknott image creation process.
- The alternative to this change is fixing the nisystemimage script. The fix looks like [this](https://github.com/shruthi-ravi/meta-nilrt/commit/1761e30d16786dcee0b952b69aac8a7552731b5c). The fix adds './' to the existing exclude paths and any additional paths provided in the cmd line. Additional changes to ninetcfgutil will also be required. These changes are not completely tested and are more risky to add at this time in the release.

2022-05-27 20:50 UTC, amstewart requested changes
To facilitate the hardknott release, I'm fine carrying this commit out-of-stream. I don't expect that upstream will want it (though we could try).

In the long term, I think it might be preferable to fixup `nisystemimage` and `ninetcfgutil`, but I understand there is more work&risk there. I'm fine carrying this patch until we get around to it.

2022-05-27 20:50 UTC, amstewart commented on meta/classes/image_types.bbclass
> +
Normally, I'm a fan of embedding whitespace fixups in my commits. But in the interest of making this commit as lightweight to carry out-of-stream as is possible, could you remove these unnecessary differences from the diff?

2022-05-27 21:29 UTC, shruthi-ravi commented
Update v2:

Reverted trailing whitespace edits to the file.

2022-05-27 21:32 UTC, chaitu236 approved these changes

2022-05-31 15:13 UTC, amstewart approved these changes

2022-05-31 15:13 UTC, merged