[kirkstone] Create new packagefeed class to make feed builds easier
ni/openembedded-core pull request #96
Opened 2023-05-22 20:12 UTC by SparkingSpork

Since we pretty much always need a package index built after feeds, it seems like having a method to designate a `packagegroup` as a `packagefeed` instead is useful. These two changes modify `package-index` to be a `package_index.bbclass` instead and adds a `packagefeed.bbclass`.

A separate PR will be posted modifying our `packagefeed-*` groups to inherit from this new structure.

## Testing:
Built locally.

2023-05-23 21:46 UTC, chaitu236 approved these changes

2023-05-24 15:48 UTC, amstewart requested changes
This looks good to me, pending the comment. I don't see any reason that upstream would reject it.

2023-05-24 15:48 UTC, amstewart commented on meta/classes/package_index.bbclass
> +# there's no reason not to build an index for them.
Upstream will probably want a more affirmative comment here, like "We must build package indexes for the SDK dummy architectures, to support scenarios where SDKs are composed from feeds."

2023-05-24 20:05 UTC, SparkingSpork commented
## V2
Updated comment to be more assertive.

2023-05-24 20:24 UTC, amstewart approved these changes

2023-05-24 21:56 UTC, SparkingSpork commented
Patch sent to upstream. Closing this PR. If upstream rejects for some odd reason, I'll move the implementation into meta-nilrt.

2023-05-24 21:56 UTC, closed without merging